
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Core
{

using System;
    using System.Collections.Generic;
    
public partial class PhanCong
{

    public int MaPC { get; set; }

    public int MaDoan { get; set; }

    public int MaNV { get; set; }

    public int MaCV { get; set; }



    public virtual ChucVu ChucVu { get; set; }

    public virtual Doan Doan { get; set; }

    public virtual NhanVien NhanVien { get; set; }

}

}
