//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuanAn()
        {
            this.Tour_QuanAn = new HashSet<Tour_QuanAn>();
        }
    
        public int MaQA { get; set; }
        public string Ten { get; set; }
        public int MaDD { get; set; }
        public string DiaChi { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour_QuanAn> Tour_QuanAn { get; set; }
    }
}
