//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
<<<<<<< HEAD
            this.ThoiGianTours = new HashSet<ThoiGianTour>();
=======
            this.Gias = new HashSet<Gia>();
>>>>>>> 40ac28184ded5cd16c479530fa6d5f537ac86221
            this.Tour_Gia = new HashSet<Tour_Gia>();
        }
    
        public int MaTour { get; set; }
        public string Ten { get; set; }
        public int DiemKhoiHanh { get; set; }
        public int DiemKetThuc { get; set; }
        public int SLNgay { get; set; }
        public int LoaiHinhDL { get; set; }
        public bool TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual DiaDiem DiaDiem1 { get; set; }
        public virtual LoaiHinhDL LoaiHinhDL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour_Gia> Tour_Gia { get; set; }
    }
}
